(ns memsearch.text.stopwords)

(def stop-words
  {"a" true
   "about" true
   "above" true
   "across" true
   "after" true
   "again" true
   "against" true
   "all" true
   "almost" true
   "alone" true
   "along" true
   "already" true
   "also" true
   "although" true
   "always" true
   "am" true
   "among" true
   "an" true
   "and" true
   "another" true
   "any" true
   "anybody" true
   "anyone" true
   "anything" true
   "anywhere" true
   "are" true
   "area" true
   "areas" true
   "aren't" true
   "around" true
   "as" true
   "ask" true
   "asked" true
   "asking" true
   "asks" true
   "at" true
   "away" true
   "b" true
   "back" true
   "backed" true
   "backing" true
   "backs" true
   "be" true
   "became" true
   "because" true
   "become" true
   "becomes" true
   "been" true
   "before" true
   "began" true
   "behind" true
   "being" true
   "beings" true
   "below" true
   "best" true
   "better" true
   "between" true
   "big" true
   "both" true
   "but" true
   "by" true
   "c" true
   "came" true
   "can" true
   "can't" true
   "cannot" true
   "case" true
   "cases" true
   "certain" true
   "certainly" true
   "clear" true
   "clearly" true
   "come" true
   "could" true
   "couldn't" true
   "d" true
   "did" true
   "didn't" true
   "differ" true
   "different" true
   "differently" true
   "do" true
   "does" true
   "doesn't" true
   "doing" true
   "don" true
   "don't" true
   "done" true
   "down" true
   "downed" true
   "downing" true
   "downs" true
   "during" true
   "e" true
   "each" true
   "early" true
   "either" true
   "end" true
   "ended" true
   "ending" true
   "ends" true
   "enough" true
   "even" true
   "evenly" true
   "ever" true
   "every" true
   "everybody" true
   "everyone" true
   "everything" true
   "everywhere" true
   "f" true
   "face" true
   "faces" true
   "fact" true
   "facts" true
   "far" true
   "felt" true
   "few" true
   "find" true
   "finds" true
   "first" true
   "for" true
   "four" true
   "from" true
   "full" true
   "fully" true
   "further" true
   "furthered" true
   "furthering" true
   "furthers" true
   "g" true
   "gave" true
   "general" true
   "generally" true
   "get" true
   "gets" true
   "give" true
   "given" true
   "gives" true
   "go" true
   "going" true
   "good" true
   "goods" true
   "got" true
   "great" true
   "greater" true
   "greatest" true
   "group" true
   "grouped" true
   "grouping" true
   "groups" true
   "h" true
   "had" true
   "hadn't" true
   "has" true
   "hasn't" true
   "have" true
   "haven't" true
   "having" true
   "he" true
   "he'd" true
   "he'll" true
   "he's" true
   "her" true
   "here" true
   "here's" true
   "hers" true
   "herself" true
   "high" true
   "higher" true
   "highest" true
   "him" true
   "himself" true
   "his" true
   "how" true
   "how's" true
   "however" true
   "i" true
   "i'd" true
   "i'll" true
   "i'm" true
   "i've" true
   "if" true
   "important" true
   "in" true
   "interest" true
   "interested" true
   "interesting" true
   "interests" true
   "into" true
   "is" true
   "isn't" true
   "it" true
   "it's" true
   "its" true
   "itself" true
   "j" true
   "just" true
   "k" true
   "keep" true
   "keeps" true
   "kind" true
   "knew" true
   "know" true
   "known" true
   "knows" true
   "l" true
   "large" true
   "largely" true
   "last" true
   "later" true
   "latest" true
   "least" true
   "less" true
   "let" true
   "let's" true
   "lets" true
   "like" true
   "likely" true
   "long" true
   "longer" true
   "longest" true
   "m" true
   "made" true
   "make" true
   "making" true
   "man" true
   "many" true
   "may" true
   "me" true
   "member" true
   "members" true
   "men" true
   "might" true
   "more" true
   "most" true
   "mostly" true
   "mr" true
   "mrs" true
   "much" true
   "must" true
   "mustn't" true
   "my" true
   "myself" true
   "n" true
   "necessary" true
   "need" true
   "needed" true
   "needing" true
   "needs" true
   "never" true
   "new" true
   "newer" true
   "newest" true
   "next" true
   "no" true
   "nobody" true
   "non" true
   "noone" true
   "nor" true
   "not" true
   "nothing" true
   "now" true
   "nowhere" true
   "number" true
   "numbers" true
   "o" true
   "of" true
   "off" true
   "often" true
   "old" true
   "older" true
   "oldest" true
   "on" true
   "once" true
   "one" true
   "only" true
   "open" true
   "opened" true
   "opening" true
   "opens" true
   "or" true
   "order" true
   "ordered" true
   "ordering" true
   "orders" true
   "other" true
   "others" true
   "ought" true
   "our" true
   "ours" true
   "ourselves" true
   "out" true
   "over" true
   "own" true
   "p" true
   "part" true
   "parted" true
   "parting" true
   "parts" true
   "per" true
   "perhaps" true
   "place" true
   "places" true
   "point" true
   "pointed" true
   "pointing" true
   "points" true
   "possible" true
   "present" true
   "presented" true
   "presenting" true
   "presents" true
   "problem" true
   "problems" true
   "put" true
   "puts" true
   "q" true
   "quite" true
   "r" true
   "rather" true
   "really" true
   "right" true
   "room" true
   "rooms" true
   "s" true
   "said" true
   "same" true
   "saw" true
   "say" true
   "says" true
   "second" true
   "seconds" true
   "see" true
   "seem" true
   "seemed" true
   "seeming" true
   "seems" true
   "sees" true
   "several" true
   "shall" true
   "shan't" true
   "she" true
   "she'd" true
   "she'll" true
   "she's" true
   "should" true
   "shouldn't" true
   "show" true
   "showed" true
   "showing" true
   "shows" true
   "side" true
   "sides" true
   "since" true
   "small" true
   "smaller" true
   "smallest" true
   "so" true
   "some" true
   "somebody" true
   "someone" true
   "something" true
   "somewhere" true
   "state" true
   "states" true
   "still" true
   "such" true
   "sure" true
   "t" true
   "take" true
   "taken" true
   "than" true
   "that" true
   "that's" true
   "the" true
   "their" true
   "theirs" true
   "them" true
   "themselves" true
   "then" true
   "there" true
   "there's" true
   "therefore" true
   "these" true
   "they" true
   "they'd" true
   "they'll" true
   "they're" true
   "they've" true
   "thing" true
   "things" true
   "think" true
   "thinks" true
   "this" true
   "those" true
   "though" true
   "thought" true
   "thoughts" true
   "three" true
   "through" true
   "thus" true
   "to" true
   "today" true
   "together" true
   "too" true
   "took" true
   "toward" true
   "turn" true
   "turned" true
   "turning" true
   "turns" true
   "two" true
   "u" true
   "under" true
   "until" true
   "up" true
   "upon" true
   "us" true
   "use" true
   "used" true
   "uses" true
   "v" true
   "very" true
   "w" true
   "want" true
   "wanted" true
   "wanting" true
   "wants" true
   "was" true
   "wasn't" true
   "way" true
   "ways" true
   "we" true
   "we'd" true
   "we'll" true
   "we're" true
   "we've" true
   "well" true
   "wells" true
   "went" true
   "were" true
   "weren't" true
   "what" true
   "what's" true
   "when" true
   "when's" true
   "where" true
   "where's" true
   "whether" true
   "which" true
   "while" true
   "who" true
   "who's" true
   "whole" true
   "whom" true
   "whose" true
   "why" true
   "why's" true
   "will" true
   "with" true
   "within" true
   "without" true
   "won't" true
   "work" true
   "worked" true
   "working" true
   "works" true
   "would" true
   "wouldn't" true
   "x" true
   "y" true
   "year" true
   "years" true
   "yet" true
   "you" true
   "you'd" true
   "you'll" true
   "you're" true
   "you've" true
   "young" true
   "younger" true
   "youngest" true
   "your" true
   "yours" true
   "yourself" true
   "yourselves" true
   "z" true})
